cc_library(
    name = "content_pty_session",
    srcs = ["content_pty_session.cc"],
    hdrs = ["content_pty_session.h"],
    visibility = ["//src/parent:__pkg__"],
    deps = [
        "//src/base:file_descriptor",
        "//src/base:owned_file_descriptor",
        "//src/base:process_id",
        "//src/base:terminal_size",
        "//third_party/system:libutil",
    ],
)

cc_library(
    name = "terminal_screen",
    srcs = ["terminal_screen.cc"],
    hdrs = [
        "terminal_position.h",
        "terminal_screen.h",
    ],
    visibility = ["//src/parent:__pkg__"],
    deps = [
        "//src/base:terminal_size",
        "//third_party/system:libvterm_neovim",
    ],
)

cc_test(
    name = "terminal_screen_test",
    srcs = ["terminal_screen_test.cc"],
    deps = [
        ":terminal_screen",
        "@googletest//:gtest_main",
    ],
    tags = ["unit"],
)
