cc_library(
    name = "application_message_discriminators",
    hdrs = ["application_message_discriminators.h"],
    visibility = ["//src/bridge/browser:__pkg__"],
)

cc_library(
    name = "application_message_codec",
    srcs = ["application_message_codec.cc"],
    hdrs = [
        "application_message_codec.h",
        "bridge_to_browser_message.h",
        "browser_to_bridge_message.h",
    ],
    visibility = ["//src/bridge/server:__pkg__"],
    deps = [":application_message_discriminators"],
)

cc_library(
    name = "browser_terminal_input",
    hdrs = ["browser_terminal_input.h"],
)

cc_library(
    name = "browser_terminal_resize",
    hdrs = ["browser_terminal_resize.h"],
    deps = ["//src/base:terminal_size"],
)

cc_library(
    name = "browser_application_message",
    hdrs = ["browser_application_message.h"],
    deps = [
        ":browser_terminal_input",
        ":browser_terminal_resize",
        "//src/parent/input/command:parent_input_commands",
    ],
)

cc_library(
    name = "browser_application_message_parser",
    srcs = ["browser_application_message_parser.cc"],
    hdrs = ["browser_application_message_parser.h"],
    visibility = ["//src/bridge:__pkg__"],
    deps = [
        ":application_message_codec",
        ":browser_application_message",
    ],
)

cc_test(
    name = "application_message_codec_test",
    srcs = ["application_message_codec_test.cc"],
    deps = [
        ":application_message_codec",
        ":application_message_discriminators",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "browser_application_message_parser_test_support",
    testonly = True,
    srcs = ["browser_application_message_parser_test_support.cc"],
    hdrs = ["browser_application_message_parser_test_support.h"],
    deps = [
        ":browser_application_message_parser",
        "@googletest//:gtest",
    ],
)

cc_test(
    name = "browser_parent_command_message_parser_test",
    srcs = ["browser_parent_command_message_parser_test.cc"],
    deps = [
        ":browser_application_message_parser",
        ":browser_application_message_parser_test_support",
        "@googletest//:gtest_main",
    ],
    tags = ["unit"],
)

cc_test(
    name = "browser_terminal_message_parser_test",
    srcs = ["browser_terminal_message_parser_test.cc"],
    deps = [
        ":browser_application_message_parser",
        ":browser_application_message_parser_test_support",
        "@googletest//:gtest_main",
    ],
    tags = ["unit"],
)

test_suite(
    name = "browser_application_message_parser_test",
    tests = [
        ":browser_parent_command_message_parser_test",
        ":browser_terminal_message_parser_test",
    ],
    tags = ["unit"],
)
