cc_library(
    name = "process_exit_status",
    srcs = ["process_exit_status.cc"],
    hdrs = ["process_exit_status.h"],
    visibility = [
        "//src/parent:__pkg__",
        "//src/parent/terminal:__pkg__",
        "//src/parent/tray:__pkg__",
        "//src/parent/worktree/overlay:__pkg__",
    ],
)

cc_library(
    name = "command_runner",
    srcs = ["command_runner.cc"],
    hdrs = [
        "command_result.h",
        "command_runner.h",
        "standard_output_mode.h",
    ],
    visibility = ["//src/parent/worktree:__pkg__"],
    deps = [
        ":process_exit_status",
        "//src/base:file_descriptor",
        "//src/base:owned_file_descriptor",
        "//src/base:process_id",
    ],
)

cc_binary(
    name = "fake_command",
    testonly = True,
    srcs = ["fake_command.cc"],
)

cc_test(
    name = "command_runner_test",
    srcs = ["command_runner_test.cc"],
    data = [":fake_command"],
    deps = [
        ":command_runner",
        "@googletest//:gtest_main",
    ],
    tags = ["unit"],
)
