cc_library(
    name = "environment_guard",
    hdrs = ["environment_guard.h"],
    visibility = [
        "//src/parent:__pkg__",
        "//src/parent/worktree:__pkg__",
    ],
)

cc_library(
    name = "test_paths",
    hdrs = ["test_paths.h"],
    visibility = [
        "//src/parent/worktree:__pkg__",
        "//src/parent/worktree/overlay:__pkg__",
    ],
)
