package_group(
    name = "src_packages",
    packages = ["//src/..."],
)

cc_library(
    name = "file_descriptor",
    hdrs = ["file_descriptor.h"],
    visibility = [":src_packages"],
)

cc_library(
    name = "owned_file_descriptor",
    hdrs = ["owned_file_descriptor.h"],
    visibility = [":src_packages"],
    deps = [":file_descriptor"],
)

cc_library(
    name = "process_id",
    hdrs = ["process_id.h"],
    visibility = [":src_packages"],
)

cc_test(
    name = "process_id_test",
    srcs = ["process_id_test.cc"],
    deps = [
        ":process_id",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "network_port",
    hdrs = ["network_port.h"],
    visibility = [":src_packages"],
)

cc_library(
    name = "terminal_size",
    hdrs = ["terminal_size.h"],
    visibility = [":src_packages"],
)

cc_test(
    name = "network_port_test",
    srcs = ["network_port_test.cc"],
    deps = [
        ":network_port",
        "@googletest//:gtest_main",
    ],
)
